CONFIG_FILE_NAME    = 'configfile.ini'
OPEN_TEXT_MODE      = 'w'
LABEL_SEPARATOR     = ','

PATH        = 'Path'
TEMPLATE    = 'Template'
PROJECT     = 'Project'
METADATA    = 'Metadata'
OUTPUT      = 'Output'

PACKAGES    = 'Packages'
PACKAGE     = 'Package'
MODEL       = 'Model'

LABEL   = 'Label'
LABELS  = 'Labels'
    
DOCUMENT        = 'Document'
PREPARED_FOR    = 'Prepared_for'
DEVELOPER       = 'Developer'
IDD             = 'IDD'

DOCUMENT_SECTION    = 'Document_section'
CHANGE_RECORD       = 'Change_record'
APPROVERS           = 'Approvers'
ESTIMATES           = 'Estimates'
PERFORMANCE         = 'Performance'
ASSUMPTIONS         = 'Assumptions'
REVIEWER            = 'Reviewer'
ENTRY_EXIT          = 'Entry_and_exit'
UNIT_TEST           = 'Unit_test'
UPGRADABILITY       = 'Upgradability'

OVERVIEW            = 'Overview'
OBJECTIVE           = 'Objective'
AUDIENCE            = 'Audience'
ACRONYM             = 'Acronym'
ACRONYM_DESC        = 'Acronym_description'
REFERENCE_DOC       = 'Reference_document'
REFERENCE_DESC      = 'Reference_description'
PURPOSE_OVERVIEW    = 'Purpose_overview'

CUSTOMISATION   = 'Customisation'
CODE_COLUMN     = 'Code_column'
TABLE_STYLE     = 'Table_style'
HEADER_1        = 'Header1'
HEADER_2        = 'Header2'
HEADER_3        = 'Header3'
HEADER_4        = 'Header4'
HEADER_5        = 'Header5'
HEADER_6        = 'Header6'

TRUE_VALUE = 'True'

CONFIG_ERROR = 'Error while creating/updating config file.'
CONFIG_READ_ERROR = 'Error while reading from config file'