# XML parse elements

XML = 'xml'
CONTENT = 'Content'
INCLUDE = 'Include'
BACKWARD_SLASH = '\\'
COMPOSITEENTITYLIST = ['Entity', 'Remark']
DATAENTITY = 'DataEntity'
BLANK = ''
ATSIGN = '@'
SEPRATOR = ':'
NAME = 'Name'
DS_TYPE = 'DataSource type'
DSTYPE = 'DataSourceType'
QUERY = 'Query'
REPORTDS = 'AxReportDataSet'
DATAFIELD = 'DataField'
DATA_FIELD = 'Data field'
REMARK = 'Remark'
KEYS = 'Keys'
SOURCECODE = 'SourceCode'
SOURCECODE_V6 = '{Microsoft.Dynamics.AX.Metadata.V6}SourceCode'