# TDD variables
TEMPLATE_TXT = 'Select template'
PROJECT_TXT = 'Select project'
METADATA_TXT = 'Select metadata folder'
OUTPUT_TXT = 'Select output folder'
OUTPUT_FILE_NAME = ''
PACKAGE_NAME = 'Package name'
MODEL_NAME = 'Model name'
IDD_NAME = 'IDD name'
CUST_NAME = 'Customer name'
DEVELOPER_NAME = 'Developer name'
OBJECTIVE_TXT = 'This document provides a comprehensive and detailed Low-Level Design of the system, using several different technical components to depict different features of the system'
AUDIENCE_TXT = 'Enterprise Architecture|Business Sponsor|Project Manager and Project Team|Build Team|Support Team'
ACRONYM_TXT = ''
ACRONYM_DESC_TXT = ''
REF_DOCUMENT_TXT = 'Functional Design Document'
REF_DESC_TXT = 'Functional Design Document(s) describes the implementation approach of the business requirements collected to ensure the end product meets the business objectives.'
PURPOSE_OVERVIEW_TXT = 'This document specifies technical details regarding the components involved in an MS implementation. It serves as a blueprint for the programmers to follow, provides guidance to the software developers, and discusses customizing certain components on top of Dynamics 365. This document is designed to be used in conjunction with a functional design document.'
HEADER_NUM_1_TXT = 'NumHeading_1'
HEADER_NUM_2_TXT = 'NumHeading_2'
HEADER_NUM_3_TXT = 'NumHeading_3'
HEADER_NUM_4_TXT = 'NumHeading_4'
HEADER_NUM_5_TXT = 'NumHeading_5'
HEADER_NUM_6_TXT = 'NumHeading_6'
TABLE_TXT = 'TDD Style'
LABELS_LIST = []
LABELS_DICT = {}
CHANGE_RECORD_CHECKED = True
REVIEWER_CHECKED = True
APPROVER_CHECKED = True
ENTRYANDEXIT_CHECKED = True
ESTIMATES_CHECKED = True
UNITTEST_CHECKED = True
PERFORMANCE_CHECKED = True
UPGRADABILITY_CHECKED = True
ASSUMPTIONS_CHECKED = True
CODE_COLUMN_CHECKED = True
TODAY = ''
OBJECT_PATH = ''